### ISSUE TITLE
Fix L2A loading issue

### ISSUE THREAD

**Issue by MarcCoru** [TUM-LMF/BreizhCrops#13]
Band sequence of L2A loading is not correct.
fix via if-else case on level

https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/examples/train.py#L73

**Comment by charlotte-pel** [comment]
Missing level parameter when loading frh04
https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/examples/train.py#L97
