### ISSUE TITLE
fix missing if statement 

### ISSUE THREAD

**Issue by charlotte-pel** [TUM-LMF/BreizhCrops#15]
Is a if statement on level missing [here](https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/breizhcrops/datasets/breizhcrops.py#L165)?

**Comment by MarcCoru** [comment]
the geodataframe (shapefile) should be the same for both L1C and L2A, but I see that it may break with wrong column names for the L1C vs L2A index file. In particular `meanQA60` vs `meanCLD`

### L1C
```
self.index.columns
Out[1]: Index(['CODE_CULTU', 'path', 'meanQA60', 'sequencelength'], dtype='object')
```
### L2A
```
self.index.columns
Out[3]: Index(['CODE_CULTU', 'path', 'meanCLD', 'sequencelength'], dtype='object')
```

I would prefer renaming the columns in the `__init__` function to be consistent and fixing the column names by a specific test. Columnnames 'CODE_CULTU', 'path', 'meanCLD', 'sequencelength' sound  reasonable for me. What do you think?

**Comment by charlotte-pel** [comment]
I am happy with your solution as long it consistent.
meanCLD sounds more understandable.
